# Generated by Django 4.2.11 on 2024-07-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_civilstatus_item_civil_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='birthplace',
            new_name='bloodtype',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='gender',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='religion',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='tertiary',
            new_name='zip_code',
        ),
    ]
